name: Deploy

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
         
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print variables
        run: echo "${{ secrets.GITHUB_TOKEN }}"

      - name: setup
        uses: actions/setup-node@v4
        with: 
          node-version: '18'

      - name: Install dependencies
        run: npm install
      
      - name: run test
        run: npm run test
        
      - name: Build
        run: npm run build

      - name: Deploy
        run: npm run deploy
